dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - git

script:
  - git fetch --all
  - git reset --hard origin/master
  - git submodule update --init
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake -D ENABLE_COVERAGE:BOOL=TRUE . 
  - cmake --build . -- -j2
  - ctest
